# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog.DemingFactor
email: online@demingfactor.com
description: DemingFactor is an Media Design consultancy that thrives at the intersection of Digital and Graphic Design. We design packaging, branding and identities, installations, products, posters, websites and apps.

aboutPage: true

paginate: 20

disqus: false
disqus_shortname: 'your-disqus-shortname'

baseurl: "/" # /DemingFactor-blog the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DemingFactor
github_username:  DemingFactor
permalink:       /:year/:title/

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima
plugins:
  - jekyll-feed


# defaults:
#     -
#         scope:
#             path: "" # empty string for all files
#             type: pages
#         values:
#             layout: default
#     -
#         scope:
#             path: "" # empty string for all files
#             type: posts
#         values:
#             layout: post
#     -
#         scope:
#             path: ""
#             type: drafts
#         values:
#             layout: post
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
